name: Deploy to EKS

on:
  push:
    branches:
      - master  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to ECR
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: latest
        IMAGE_NAME: sagikazarmark/dvwa
        AWS_ACCOUNT_ID: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker pull $IMAGE_NAME
        # docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $IMAGE_NAME $ECR_REPOSITORY:$IMAGE_TAG
        echo "Pushing image to ECR: $AWS_ACCOUNT_ID/$ECR_REPOSITORY:$IMAGE_TAG"
        docker push $ECR_REPOSITORY:$IMAGE_TAG

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f K8s/deployment.yaml
        kubectl apply -f K8s/service.yaml
